//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Departmant
    {
        public int Id { get; set; }
        public string DepartmanName { get; set; }
        public int DefaultMenu_Id { get; set; }
        public int Screen_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
    
        public virtual User_Roles User_Roles { get; set; }
    }
}
