//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int Id { get; set; }
        public bool DayOperations { get; set; }
        public bool POS { get; set; }
        public bool Addition { get; set; }
        public bool Accounts { get; set; }
        public bool Stockt { get; set; }
        public bool Reporting { get; set; }
        public bool Setting { get; set; }
        public bool nulllll { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
